# SPDX-License-Identifier: 0BSD
"""Get the passphrase word list."""

def get_wordlist() -> tuple:
    wordlist = (
        "the", "and", "was", "for", "his", "are", "had", "has", "its",
        "she", "new", "one", "her", "who", "but", "not", "two", "all", "may",
        "him", "out", "can", "war", "won", "end", "use", "due", "amp", "now",
        "day", "age", "did", "any", "set", "own", "law", "led", "art", "cup",
        "son", "top", "old", "air", "off", "six", "way", "act", "you", "few",
        "win", "men", "man", "san", "per", "run", "red", "how", "see", "sea",
        "get", "ten", "car", "via", "big", "saw", "los", "bay", "put", "too",
        "met", "low", "far", "hit", "ran", "our", "van", "sir", "era", "got",
        "key", "oil", "ice", "cvv", "god", "lee", "yet", "hot", "cut", "gas",
        "job", "von", "sun", "bus", "bbc", "pay", "del", "tom", "bar", "pop",
        "box", "boy", "tax", "joe", "inc", "gun", "sex", "say", "usa", "fox",
        "bad", "lot", "etc", "aid", "com", "bob", "let", "jim", "nfl", "des",
        "why", "sri", "dam", "die", "ali", "try", "eye", "ben", "don", "pro",
        "dry", "sam", "row", "web", "ltd", "dvd", "map", "leg", "der", "nor",
        "ray", "ceo", "max", "dog", "kim", "sky", "gay", "las", "ago", "mrs",
        "rio", "dan", "dna", "fan", "nba", "arm", "net", "fly", "abc", "ibn",
        "tim", "ban", "jan", "duo", "nhl", "oak", "ann", "les", "mix", "lay",
        "buy", "cbs", "tie", "roy", "guy", "aim", "gap", "bit", "phd", "fit",
        "bid", "ian", "pan", "tag", "ref", "add", "lap", "raf", "nbc", "mac",
        "hip", "ill", "mid", "raw", "cap", "fee", "bed", "fun", "cat", "tea",
        "uss", "abu", "lie", "jay", "sat", "rev", "ken", "sum", "leo", "ski",
        "han", "cdp", "bin", "ask", "hms", "inn", "ron", "jon", "pit", "hop",
        "liu", "rob", "eve", "ted", "eat", "tip", "wet", "lab", "jet", "bce",
        "pat", "mtv", "ram", "arc", "sox", "hub", "afc", "afl", "vii", "bow",
        "app", "bat", "fed", "mlb", "sit", "zoo", "joy", "und", "fbi", "egg",
        "kid", "pen", "hat", "hiv", "den", "fat", "vol", "amy", "wwe", "ibm",
        "rap", "cox", "mad", "ash", "kit", "spy", "nsw", "col", "atp", "ore",
        "ion", "lit", "log", "mps", "ace", "ufc", "www", "rod", "das", "gen",
        "dos", "jam", "odd", "cia", "sin", "llc", "tin", "org", "pub", "tel",
        "sec", "ana", "pet", "fur", "toy", "utc", "mud", "bag", "mvp", "yes",
        "bee", "rao", "rna", "sue", "fin", "uci", "vfl", "ear", "tan", "mar",
        "itv", "ham", "lok", "mit", "mhz", "lou", "wei", "eva", "rbi", "jin",
        "chi", "rpm", "rey", "cao", "mob", "cry", "gdp", "ira", "sad", "non",
        "raj", "aka", "icc", "fcc", "hay", "iso", "rat", "pga", "mls", "sur",
        "bet", "pin", "pot", "spa", "hbo", "lin", "mph", "kay", "gym", "cbc",
        "cnn", "rex", "rca", "bmw", "min", "dot", "con", "pbs", "rim", "phi",
        "est", "cal", "usc", "ivy", "crc", "cow", "goa", "ink", "pig", "acc",
        "dee", "bye", "fix", "sen", "rue", "jaw", "tai", "xii", "cab", "yan",
        "nhs", "plc", "emi", "vic", "hal", "sub", "nrl", "ads", "mgm", "uae",
        "wta", "ios", "owl", "par", "cds", "hut", "rai", "dei", "fog", "dug",
        "hon", "wwf", "mel", "var", "zhu", "aft", "doc", "mba", "fda", "ole",
        "cum", "rfc", "usd", "shi", "tap", "val", "liz", "odi", "mir", "sda",
        "chu", "lip", "hua", "rms", "tcp", "udp", "dns", "ftp", "ssh", "ssl",
        "tls", "vpn", "lan", "wan", "arp", "nat", "url", "cpu", "gpu", "hdd",
        "ssd", "usb", "vga", "dvi", "nas", "lcd", "ide", "api", "sdk", "gui",
        "cli", "php", "sql", "xml", "css", "jvm", "dll", "exe", "oop", "git",
        "vim", "drm", "csv", "soc", "ips", "aes", "aws", "vds", "osi", "koi",
        "utf", "jdk", "jre", "aac", "apk", "avi", "asm", "awk", "txt", "jpg",
        "png", "foo", "bak", "pdf", "psk", "wep", "wpa", "bmp", "cpp", "gsm",
        "cmd", "lte", "deb", "dnf", "dng", "pkg", "apt", "adb", "efi", "zip",
        "zst", "gpg", "lzo", "lzw", "lua", "ogg", "mov", "msi", "ndk", "neo",
        "nfc", "nft", "obj", "rar", "gif", "rsa", "pgp", "sfx", "sig", "tar",
        "taz", "tbz", "tgz", "txz", "vbr", "crf", "wav", "wma", "wps", "xls",
        "yml", "ppt", "bsd", "isc", "gpl", "mpl", "sil", "sed", "sfw", "eng",
        "rus", "jap", "mot", "alt", "gov", "dpi", "nsa", "kgb", "mvd", "pix",
        "lto", "ado", "zig", "lms", "ppa", "srv", "dev", "mnt", "sys", "tmp",
        "sus", "sas", "ttf", "dex", "oga", "aga", "mkv"
    )
    return wordlist
